version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "443:443"
        networks:
            - default
        volumes:
            - ./src:/src
            - ./certs:/certs
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./logs:/var/log/nginx/
    php:
        image: php:fpm
        networks:
            - default
        volumes:
            - ./src:/src

networks:
    default:
        driver: bridge